import Head from "next/head";
import styles from "../styles/Home.module.css";
import Layout from "..pages/layout.js";




export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
            href="https://fonts.googleapis.com/css2?family=Mulish:wght@200;600;800&display=swap"
            rel="stylesheet"
          />
   
      </Head>
      <main>
        <Layout />
      </main>
    </>
  );
}
