import Head from "next/head";
import Image from "next/image";
import { Inter,Lexend_Deca, Quicksand} from "@next/font/google";
import styles from "../styles/Home.module.css";
import Layout from "./components/Layout/Layout";




const lexend= Lexend_Deca({ 
  weight: ['400', '900'],
  subsets: ["latin"] });

  const quickSand = Quicksand({subsets:["latin"]})


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<main>
<Layout/>
</main>


      
          </>
  );
}
